### ISSUE TITLE
pytest-runner sometimes picks wrong package to install

### ISSUE THREAD

**Issue by mortenlj** [pytest-dev/pytest-runner#11]
I'm not 100% sure this is pytest-runner, or something else, but it only happens when using the pytest-runner to run tests so I figured I'd start here. It's also doesn't happen consistently, so it's difficult to reproduce, but I guess starting an issue would be a way to start iterating over how to figure out what's happening.

In a recent build, I had this happen:

```
build	29-Feb-2016 13:29:51	Searching for pytest
build	29-Feb-2016 13:29:51	Best match: pytest sugar-0.5.1
build	29-Feb-2016 13:29:51	Downloading https://pypi.python.org/packages/source/p/pytest-sugar/pytest-sugar-0.5.1.tar.gz#md5=23bd36427e4df0ea9244662027f42ff1
build	29-Feb-2016 13:29:51	Processing pytest-sugar-0.5.1.tar.gz
build	29-Feb-2016 13:29:51	Writing /tmp/easy_install-G4yHj9/pytest-sugar-0.5.1/setup.cfg
build	29-Feb-2016 13:29:51	Running pytest-sugar-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-G4yHj9/pytest-sugar-0.5.1/egg-dist-tmp-ar85zH
build	29-Feb-2016 13:29:51	removing '/iad/finn/bamboo-agent-1/xml-data/build-dir/FIAAS-DEPLOYDAEMON-JOB1/.eggs/pytest_sugar-0.5.1-py2.7.egg' (and everything under it)
build	29-Feb-2016 13:29:51	creating /iad/finn/bamboo-agent-1/xml-data/build-dir/FIAAS-DEPLOYDAEMON-JOB1/.eggs/pytest_sugar-0.5.1-py2.7.egg
build	29-Feb-2016 13:29:51	Extracting pytest_sugar-0.5.1-py2.7.egg to /iad/finn/bamboo-agent-1/xml-data/build-dir/FIAAS-DEPLOYDAEMON-JOB1/.eggs
build	29-Feb-2016 13:29:51	
build	29-Feb-2016 13:29:51	Installed /iad/finn/bamboo-agent-1/xml-data/build-dir/FIAAS-DEPLOYDAEMON-JOB1/.eggs/pytest_sugar-0.5.1-py2.7.egg
build	29-Feb-2016 13:29:51	Traceback (most recent call last):
build	29-Feb-2016 13:29:51	  File "/iad/finn/bamboo-agent-1/xml-data/build-dir/FIAAS-DEPLOYDAEMON-JOB1/setup.py", line 65, in <module>
build	29-Feb-2016 13:29:51	    "fiaas-deploy-daemon = fiaas_deploy_daemon:main"
build	29-Feb-2016 13:29:51	  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
build	29-Feb-2016 13:29:51	    dist.run_commands()
build	29-Feb-2016 13:29:51	  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
build	29-Feb-2016 13:29:51	    self.run_command(cmd)
build	29-Feb-2016 13:29:51	  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
build	29-Feb-2016 13:29:51	    cmd_obj.run()
build	29-Feb-2016 13:29:51	  File "build/bdist.linux-x86_64/egg/ptr.py", line 67, in run
build	29-Feb-2016 13:29:51	  File "/home/finn/.local/share/virtualenvs/fiaas-deploy-daemon/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
build	29-Feb-2016 13:29:51	    replace_conflicting=True,
build	29-Feb-2016 13:29:51	  File "/home/finn/.local/share/virtualenvs/fiaas-deploy-daemon/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
build	29-Feb-2016 13:29:51	    raise DistributionNotFound(req, requirers)
build	29-Feb-2016 13:29:51	pkg_resources.DistributionNotFound: The 'pytest' distribution was not found and is required by the application
```

When looking for pytest, it actually ends up selecting pytest-sugar, installing that, and then crashing out because pytest isn't installed. I have had a similar issue with flake8 and flake8-print. The next run might fail, and then suddenly it would work on the next run. Incidentally, pytest-sugar has already been installed by the time it gets around to trying to install pytest itself.

The relevant portions of setup.py for the run above:
```
        setup_requires=['pytest-runner', 'wheel', 'setuptools_git >= 0.3'],
        tests_require=['pytest', 'mock', 'vcrpy', 'pytest-sugar', 'pytest-html', 'pytest-cov'],
```

Any ideas about how to try and narrow down what's happening here?

**Comment by jaraco** [comment]
It's a [bug in setuptools](https://bitbucket.org/pypa/setuptools/issues/196/tests_require-pytest-pytest-cov-breaks). Place `pytest` last in your `tests_require` to work around the issue.

**Comment by sambrightman** [comment]
Maybe update [the documentation](http://doc.pytest.org/en/latest/goodpractices.html) to reflect this for now? The bug moved to pypa/setuptools#196 (with no resolution in sight).

**Comment by basaks** [comment]
`pytest` was not even installing in a virtualenv until I followed @jaraco 's solution.
