### ISSUE TITLE
Fails to download from pypi.org

### ISSUE THREAD

**Issue by msestak** [pytest-dev/pytest-runner#41]
When I try to download superset it fails on resolving dependencies for  pydruid package.

Error is below:
[root@tardis python36]# /root/pydev/py36-venv/bin/pip download --proxy=http://proxyuser:proxypass superset --dest=/tmp/python36
...
Collecting pydruid>=0.4.3 (from superset)
  File was already downloaded /tmp/python36/pydruid-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/pytest-runner/: [Errno 101] Network is unreachable -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [Errno 101] Network is unreachable -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-e3u9k_pm/pydruid/setup.py", line 44, in <module>
        include_package_data=True,
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1075, in obtain
        return installer(requirement)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "/root/pydev/py36-venv/lib64/python3.6/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-download-e3u9k_pm/pydruid/

I don't have problems downloading other packages.

Best,
Martin

**Comment by obestwalter** [comment]
> [Errno 101] Network is unreachable -- Some packages may not be found!

Did you rey again. I just installed pydruid and also pytest-runner standalone, and it works.

**Comment by msestak** [comment]
I don't have problems downloading pytest-runner standalone, only with pydruid 0.4.0 - 0.5.0.

[root@tardis superset0.22.0]# /root/pydev/py36-venv/bin/pip download --proxy=http://proxyuser:proxypass@proxy:8080 pytest-runner --dest=/tmp
Collecting pytest-runner
  Using cached https://files.pythonhosted.org/packages/72/a4/d7a5738a3096f22a98bec1609e237b250ebff04e5ea2930305d485337263/pytest_runner-4.2-py2.py3-none-any.whl
  Saved ./pytest_runner-4.2-py2.py3-none-any.whl
Successfully downloaded pytest-runner

Earlier versions of pydruid (0.2.x and 0.3.x) download fine. Probably pydruid issue.

**Comment by obestwalter** [comment]
> Probably pydruid issue.

I would also think so.

**Comment by jaraco** [comment]
Thanks for reporting, but I don't think there's anything reported above that implicates pytest-runner. If you find something wrong with pytest-runner, let us know.
